FROM python:3-alpine

# copy from prod
RUN apk add --no-cache mariadb-dev build-base

ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN apk update \
    && apk add mysql mysql-client \
    && apk add --no-cache --virtual .build-deps build-base \
    && apk add --no-cache gcc musl-dev python3-dev libffi-dev\
    && python -m venv /env \
    && pip install --upgrade pip


COPY ./requirements.txt ./

RUN pip install -r requirements.txt

COPY ./ ./

CMD ["flask", "run", "--host=0.0.0.0", "--debug"]
