version: "3"

services:
  web:
    build: .
    ports:
      - "8000:8000"  # Puerto donde gunicorn servir치 la aplicaci칩n
#    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Puerto donde Nginx escuchar치 las solicitudes
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Archivo de configuraci칩n de Nginx
    depends_on:
      - web
